name: Scala CLA
on: [pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Check CLA
      uses: scala/cla-checker@v1
      with:
        author: ${{ github.event.pull_request.user.login }}
